/*
 * This file is generated by jOOQ.
 */
package com.binziing.task.jooq;


import com.binziing.task.jooq.tables.TAdmin;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in xforce
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>xforce.t_admin</code>.
     */
    public static final TAdmin T_ADMIN = com.binziing.task.jooq.tables.TAdmin.T_ADMIN;
}
