/*
 * This file is generated by jOOQ.
 */
package com.binziing.task.jooq;


import com.binziing.task.jooq.tables.TAdmin;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Xforce extends SchemaImpl {

    private static final long serialVersionUID = 2059339498;

    /**
     * The reference instance of <code>xforce</code>
     */
    public static final Xforce XFORCE = new Xforce();

    /**
     * The table <code>xforce.t_admin</code>.
     */
    public final TAdmin T_ADMIN = com.binziing.task.jooq.tables.TAdmin.T_ADMIN;

    /**
     * No further instances allowed
     */
    private Xforce() {
        super("xforce", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TAdmin.T_ADMIN);
    }
}
