spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xforce?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Tangabin+23
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.binziing.task.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level.com.binziing: trace