/*
 * This file is generated by jOOQ.
 */
package com.binziing.task.jooq.tables.daos;


import com.binziing.task.jooq.tables.TAdmin;
import com.binziing.task.jooq.tables.records.TAdminRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TAdminDao extends DAOImpl<TAdminRecord, com.binziing.task.jooq.tables.pojos.TAdmin, Integer> {

    /**
     * Create a new TAdminDao without any configuration
     */
    public TAdminDao() {
        super(TAdmin.T_ADMIN, com.binziing.task.jooq.tables.pojos.TAdmin.class);
    }

    /**
     * Create a new TAdminDao with an attached configuration
     */
    @Autowired
    public TAdminDao(Configuration configuration) {
        super(TAdmin.T_ADMIN, com.binziing.task.jooq.tables.pojos.TAdmin.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer getId(com.binziing.task.jooq.tables.pojos.TAdmin object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.binziing.task.jooq.tables.pojos.TAdmin> fetchById(Integer... values) {
        return fetch(TAdmin.T_ADMIN.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.binziing.task.jooq.tables.pojos.TAdmin fetchOneById(Integer value) {
        return fetchOne(TAdmin.T_ADMIN.ID, value);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.binziing.task.jooq.tables.pojos.TAdmin> fetchByUsername(String... values) {
        return fetch(TAdmin.T_ADMIN.USERNAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.binziing.task.jooq.tables.pojos.TAdmin> fetchByPassword(String... values) {
        return fetch(TAdmin.T_ADMIN.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.binziing.task.jooq.tables.pojos.TAdmin> fetchByEmail(String... values) {
        return fetch(TAdmin.T_ADMIN.EMAIL, values);
    }
}
